all:
	gcc -std=gnu99 -o jack_in_to_out jack_in_to_out.c -ljack
	gcc -std=gnu99 -o o1 t1_.c -ljack
	gcc -std=gnu99 -o s1 t1_s.c -ljack
	gcc -std=gnu99 -o s2 t2_s.c -ljack
	gcc -std=gnu99 -o o2 t2_.c -ljack
