all:
	gcc -std=gnu99 -o ej1_2020 ej1_2020.c -ljack
	gcc -std=gnu99 -o o1 ej1_.c -ljack
	gcc -std=gnu99 -o o2 ej1s_.c -ljack
	gcc -std=gnu99 -o o4 ej3_.c -ljack
	gcc -std=gnu99 -o o3 ej2_.c -ljack -lm
