all:
	gcc -std=gnu99 -o jack_read_file jack_read_file.c -ljack -lsndfile
	gcc -std=gnu99 -o jack_read_file_samplerate jack_read_file_samplerate.c -ljack -lsndfile -lsamplerate
	gcc -std=gnu99 -o jack_write_file jack_write_file.c -ljack -lsndfile